feat: Add CreateTopicWizard view - advanced flow
Redhat-AppServices/strimzi-ui pull request #11
Opened 2020-12-09 13:45 UTC by rkpattnaik780

### Description

The UI components of Create Topics wizard - basic flow. This PR has the following UI components:

* Create Topic wizard - advanced flow
* Core Configuration Name
* Messages
* Logging

Next steps: 

* Replication
* Clean up
* Index
* Flush
* Fix the jumplinks

2020-12-09 20:18 UTC, jeff-phillips-18 requested changes

2020-12-09 20:18 UTC, jeff-phillips-18 commented on client/Elements/CreateTopicWizardWithMoreOptions/DropdownWithToggle.patternfly.tsx
> +export const DropdownWithToggle: React.FC<IDropdownWithToggleProps &
Seems like a generic component and should be placed in a more reusable directory.

2020-12-09 20:18 UTC, jeff-phillips-18 commented on client/Elements/CreateTopicWizardWithMoreOptions/CreateTopicsWizard.patternfly.css
> +  margin-bottom: 16px;
Use patternfly var for spacing ie:
```suggestion
margin-bottom: var(--pf-global--spacer--md); 
```

2020-12-10 19:41 UTC, rkpattnaik780 commented on client/Elements/CreateTopicWizardWithMoreOptions/DropdownWithToggle.patternfly.tsx
> +export const DropdownWithToggle: React.FC<IDropdownWithToggleProps &
Thanks for the suggestions @jeff-phillips-18 . I have updated my PR. Please let me know if I have placed the generic component at an appropriate place. Have added the rest of the sections as well.

2020-12-14 13:10 UTC, jeff-phillips-18 commented on client/Elements/Components/CreateTopicAdvanceWizard/CreateTopicAdvanceWizard.patternfly.css
> + }
This is in 2 PRs now (this and https://github.com/Redhat-AppServices/strimzi-ui/pull/8). We should have a common file that defines a var for the max width used for both.

2020-12-14 13:11 UTC, jeff-phillips-18 commented on client/Elements/CreateTopicWizardWithMoreOptions/DropdownWithToggle.patternfly.tsx
> +export const DropdownWithToggle: React.FC<IDropdownWithToggleProps &
generic component placement looks good.

2020-12-17 19:29 UTC, dlabaj requested changes
A few architecture changes.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/Common/DropdownWithToggle.patternfly.tsx
> +import '@patternfly/react-core/dist/styles/base.css';
We shouldn't need to import base.css here.  It should be import into this component prior to using it.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/Common/DropdownWithToggle.patternfly.tsx
> +interface IDropdownWithToggleProps {
Should be exported.  Also add comments to this interface for when we do doc generation in the future.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/Common/DropdownWithToggle.patternfly.tsx
> +/*
Can we create a component that handles the time and size instead of this Dropdown with toggle component.  It can have a label, touch spin, and the dropdown.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/CreateTopic/CreateTopicWizard.patternfly.tsx
> +import { CreateTopicAdvanceWizard } from '../CreateTopicAdvanceWizard/CreateTopicAdvanceWizard.patternfly';
Create Topic Advance Wizard should be moved into create topic wizards.  It makes sense to keep all the create topic wizard code together.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/Common/FormGroupWithPopover/FormGroupWithPopover.patternfly.tsx
> +interface IFormGroupWithPopoverProps {
Can you document the interface with comments.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/CreateTopicAdvanceWizard/CleanupSection.patternfly.tsx
> +const deleteRetentionLabelHead = 'Delete retention';
Strings need to be localized.

2020-12-17 19:29 UTC, dlabaj commented on client/Elements/Components/CreateTopicAdvanceWizard/CreateTopicAdvanceWizard.patternfly.tsx
> +  const [coreConfigData, setCoreConfigData] = useState<ICoreConfigData>({
Instead of all these state objects can you create a topic context to manage this information.  Here's an example from apicuio where we have Global state.  Since the state will only apply to a topic please create TopicContext instead of a GlobalContext.

https://github.com/Apicurio/apicurio-studio-react-poc/blob/master/packages/studio/src/context/GlobalContext.tsx

2020-12-17 21:19 UTC, dlabaj commented on client/Elements/Components/CreateTopicAdvanceWizard/CreateTopicAdvanceWizard.patternfly.tsx
> +  'topic-name': string;
Use camel case for interface properties.

2021-01-05 10:54 UTC, rkpattnaik780 commented
@dlabaj have addressed the review comments, Will handle localization of strings in a separate PR. Do have  look

2021-01-13 06:20 UTC, dlabaj approved these changes

2021-01-13 15:16 UTC, dlabaj commented
@rkpattnaik780 E2E tests are failing, can you take a look.  Thanks.

2021-01-14 19:24 UTC, merged